(lang dune 3.19)

(name kast)

(generate_opam_files true)

(source
 (github kast-lang/kast))

(authors "kuviman <kuviman@gmail.com>")

(maintainers "kuviman <kuviman@gmail.com>")

(license MIT)

(documentation https://url/to/documentation)

(package
 (name kast)
 (synopsis "a programming language")
 (description "THE programming language")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
